Repository Flagsmith/flagsmith-python-client, pull requests merged in 2024-08, with the labels that each got.

#100 fix: Offline handler not used as fallback for local evaluation mode during init
  flagsmith/flagsmith.py
  flagsmith/polling_manager.py
  flagsmith/streaming_manager.py
  tests/test_flagsmith.py
  tests/test_streaming_manager.py
Labels: fix

#101 refactor: Improve `EventStreamManager`
  flagsmith/flagsmith.py
  flagsmith/streaming_manager.py
  poetry.lock
  pyproject.toml
  tests/test_flagsmith.py
  tests/test_streaming_manager.py
Labels: refactor

#96 chore(main): release 3.8.0
  .release-please-manifest.json
  CHANGELOG.md
Labels: chore, autorelease: pending

#103 fix: Flaky `test_offline_mode__local_evaluation__correct_fallback`
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  tests/test_flagsmith.py
Labels: fix

#102 fix: Package version not bumped during automatic release
  release-please-config.json
Labels: fix

#105 chore: reset changelog to 3.7.0
  .release-please-manifest.json
  CHANGELOG.md
Labels: chore

#106 chore: single source for release-please release type
  .github/workflows/release-please.yml
  .pre-commit-config.yaml
  .release-please-manifest.json
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  tests/test_flagsmith.py
Labels: chore

#107 chore(main): release 3.8.0
  .release-please-manifest.json
  CHANGELOG.md
  pyproject.toml
Labels: chore, autorelease: pending
