Repository Flagsmith/flagsmith-python-client, pull requests merged in 2025-04, with the labels that each got.

#120 chore: add / update config files to adhere to release please requirements
  .pre-commit-config.yaml
  dependabot.yml
Labels: chore

#119 chore(main): release 3.9.0
  .release-please-manifest.json
  CHANGELOG.md
  pyproject.toml
Labels: chore, autorelease: pending

#121 ci: replace publish workflow
  .github/workflows/publish.yml
Labels: ci-cd

#122 fix: Fix HTTP requests not timing out
  flagsmith/flagsmith.py
  tests/test_flagsmith.py
Labels: fix

#123 chore(main): release 3.9.1
  .release-please-manifest.json
  CHANGELOG.md
  pyproject.toml
Labels: chore, autorelease: pending
